---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/blogs":
    post:
      summary: Create blog
      tags:
      - Blogs
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    "$ref": "#/components/schemas/blog_response"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/blog_request"
    get:
      summary: Get all blogs
      tags:
      - Blogs
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/blog_response"
  "/api/v1/blogs/{id}":
    get:
      summary: Get blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    "$ref": "#/components/schemas/blog_response"
    put:
      summary: Update blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    "$ref": "#/components/schemas/blog_response"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/blog_request"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  schemas:
    blog_response:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
    blog_request:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
      - title
      - content
